### ISSUE TITLE
Error encountered when running the app

### ISSUE THREAD

**Issue by kylelhk** [kylelhk/Pictionary#3]
I've just got the below error about the version of Werkzeug when running `flask run`:

<img width="524" alt="image" src="https://github.com/kylelhk/Pictionary/assets/116782485/38a3d073-72d7-4e98-b40f-1069741544f5">

If you guys encounter the same error, please try following the steps below by which I've managed to resolve the error:

1. Deactivate your current environment:
`deactivate`

2. Remove the virtual environment folder:
`rm -rf venv`

3. Create a new virtual environment and reinstall dependencies:
`python -m venv venv`
`source venv/bin/activate  # Use venv\Scripts\activate on Windows`
`pip install -r requirements.txt`

Feel free to discuss if any issue.  Thanks.

**Comment by trieuH** [comment]
I had the same issues too, it seems like the issue may be to do with incompability due to different versions of flask and werkzeug. It seems like werkzeug has deprecated the url_decode command in its latest version, which is what's causing the import error. Please see these links for more information:
https://werkzeug.palletsprojects.com/en/3.0.x/changes/#version-3-0-1 
https://github.com/pallets/werkzeug/issues/2600

Rolling back to older versions of flask and werkzeug fixed the issue for me, and I've changed the requirements.txt file in my pull request above. We may need to have a look at our current code and packages to decide whether:  
-  We should use the older Flask and werkzeug packages, and make sure it doesn't affect any of our current code.
- Use newer versions of Flask and werkzeug, and refactor our current code to remove deprecated functions.

**Comment by kylelhk** [comment]
Thanks Trieu.  This issue has been solved in Issue #6.  Everyone can run the app now.
